id=PIXIPlugin
class=org.nrg.xnatx.plugins.pixi.PIXIPlugin
name=PIXI Plugin
beanName=pIXIPlugin
entityPackages=org.nrg.xnatx.plugins.pixi.xenografts.entities, org.nrg.xnatx.plugins.pixi.hotelsplitter.entities
logConfiguration=pixi-logback.xml
dataModel.pixi.animalDemographicData.secured=true
dataModel.pixi.animalDemographicData.singular=Animal Demographic Data
dataModel.pixi.animalDemographicData.plural=Animal Demographics
dataModel.pixi.animalDemographicData.code=AD
dataModel.pixi.pdxData.secured=true
dataModel.pixi.pdxData.singular=PDX
dataModel.pixi.pdxData.plural=PDXs
dataModel.pixi.pdxData.code=PDX
dataModel.pixi.cellLineData.secured=true
dataModel.pixi.cellLineData.singular=Cell Line
dataModel.pixi.cellLineData.plural=Cell Lines
dataModel.pixi.cellLineData.code=CL
dataModel.pixi.weightData.secured=true
dataModel.pixi.weightData.singular=Weight
dataModel.pixi.weightData.plural=Weights
dataModel.pixi.weightData.code=WT
dataModel.pixi.drugTherapyData.secured=true
dataModel.pixi.drugTherapyData.singular=Drug Therapy
dataModel.pixi.drugTherapyData.plural=Drug Therapies
dataModel.pixi.drugTherapyData.code=DT
dataModel.pixi.caliperMeasurementData.secured=true
dataModel.pixi.caliperMeasurementData.singular=Caliper Measurement
dataModel.pixi.caliperMeasurementData.plural=Caliper Measurements
dataModel.pixi.caliperMeasurementData.code=CM
dataModel.pixi.hotelScanRecord.secured=true
dataModel.pixi.hotelScanRecord.singular=Hotel Scan Record
dataModel.pixi.hotelScanRecord.plural=Hotel Scan Records
dataModel.pixi.hotelScanRecord.code=HSR
dataModel.pixi.hotel.secured=true
dataModel.pixi.hotel.singular=Hotel
dataModel.pixi.hotel.plural=Hotels
dataModel.pixi.hotel.code=HTL
dataModel.pixi.animalHusbandryData.secured=true
dataModel.pixi.animalHusbandryData.singular=Animal Husbandry
dataModel.pixi.animalHusbandryData.plural=Animal Husbandry
dataModel.pixi.animalHusbandryData.code=AH
dataModel.pixi.imageAcquisitionContextAssessorData.secured=true
dataModel.pixi.imageAcquisitionContextAssessorData.singular=Image Acquisition Context
dataModel.pixi.imageAcquisitionContextAssessorData.plural=Image Acquisition Contexts
dataModel.pixi.imageAcquisitionContextAssessorData.code=IAC
dataModel.pixi.bliSessionData.secured=true
dataModel.pixi.bliSessionData.singular=BLI Session
dataModel.pixi.bliSessionData.plural=BLI Sessions
dataModel.pixi.bliSessionData.code=BLI
dataModel.pixi.bliScanData.secured=true
dataModel.pixi.bliScanData.singular=BLI Scan
dataModel.pixi.bliScanData.plural=BLI Scans
dataModel.pixi.bliScanData.code=BLIScan
