###
### PIXI Module Script
###

pixiModuleScript:
  tag: script|src="~/scripts/xnat/plugin/pixi/pixi-module.js"

###
### Demographic Data Implementation Preference
###

subjectDisplayPreferencesForm:
  kind: panel.form
  id: subjectDisplayPreferencesForm
  name: subjectDisplayPreferencesForm
  label: Subject Display Preferences
  method: POST
  contentType: json
  url: /xapi/pixi/preferences
  contents:
    ${demographicDataImpl}
    ${uiShowHumanSearchFields}

demographicDataImpl:
  kind: panel.select.single
  name: demographicDataImpl
  label: Demographic Data Type
  description: >
    Select a preferred demographic data type to be used when creating new subjects. Projects can also select there own
    preference.
  options:
    xnat:
      label: "xnat:demographicData"
      value: "xnat:demographicData"
    pixi:
      label: "pixi:animalDemographicData"
      value: "pixi:animalDemographicData"

uiShowHumanSearchFields:
  kind: panel.input.switchbox
  name: uiShowHumanSearchFields
  label: Display Huamn Search Fields
  description: >
    Display human search fields on the home page and in the advanced search.

###
### Species Preferences
###

speciesPreferencesPanel:
  kind: panel
  name: speciesPreferencesPanel
  label: Species
  contents:
    speciesPreferencesTable:
      tag: "div#species-preferences-manager"
    speciesPreferencesScript:
      tag: script|src="~/scripts/xnat/plugin/pixi/pixi-speciesPreferences.js"
    renderSpeciesPreferencesTable:
      tag: script
      content: >
        XNAT.plugin.pixi.speciesPreferenceManager.init('#species-preferences-manager');

###
### Vendor Preferences
###

vendorPreferencesPanel:
  kind: panel
  name: vendorPreferencesPanel
  label: Animal Vendors / Suppliers
  contents:
    vendorPreferencesTable:
      tag: "div#vendor-preferences-manager"
    vendorPreferencesScript:
      tag: script|src="~/scripts/xnat/plugin/pixi/pixi-vendorPreferences.js"
    renderVendorPreferencesTable:
      tag: script
      content: >
        XNAT.plugin.pixi.vendorPreferenceManager.init('#vendor-preferences-manager');

###
### PDXs
###

pdxPanel:
  kind: panel
  name: pdxPanel
  label: Patient-Derived Xenografts
  contents:
    pdxPreferencesTable:
      tag: "div#pdx-manager"
    xenograftScript: ## Needed for PDXs and Cell Lines
      tag: script|src="~/scripts/xnat/plugin/pixi/pixi-xenograft.js"
    renderPdxPreferencesTable:
      tag: script
      content: >
        XNAT.plugin.pixi.pdxManager.init('#pdx-manager');

###
### Cell Lines
###

cellLinePanel:
  kind: panel
  name: cellLinePanel
  label: Cell Lines
  contents:
    cellLinePreferencesTable:
      tag: "div#cell-line-manager"
    renderCellLinePreferencesTable:
      tag: script
      content: >
        XNAT.plugin.pixi.cellLineManager.init('#cell-line-manager');

###
### Mouse Hotels
###

hotelPanel:
  kind: panel
  name: hotelPanel
  label: Hotel Preferences
  contents:
    hotelDescription:
      tag: div.message
      contents:
        "This panel lists all of the 'mouse hotels' which can be used with the hotel image session splitter. They describe the relative position of a subject in the image pixel data. These hotels capture DICOMs 'Subject Relative Position in Image' attribute."
    hotelContainer:
      tag: "div#hotel-preferences-manager"
    hotelPreferencesJs:
      tag: script|src="~/scripts/xnat/plugin/pixi/pixi-hotelPreferences.js"
    renderHotelTable:
      tag: script
      content: >
        XNAT.plugin.pixi.hotelPreferenceManager.init('#hotel-preferences-manager');

#################################################
####  Root Site Admin Spawner Config Object  ####
#################################################

siteSettings:
  kind: tabs
  name: pixiAdminPage
  label: Administer PIXI
  meta:
    tabGroups:
      pixiTabGroup: PIXI
  contains: tabs
  tabs:
    subjectSettingsTab:
      kind: tab
      name: subjectSettingsTab
      label: Subject Settings
      group: pixiTabGroup
      active: true
      contents:
        ${pixiModuleScript}
        ${subjectDisplayPreferencesForm}
        ${speciesPreferencesPanel}
        ${vendorPreferencesPanel}
    xenograftSettingsTab:
      kind: tab
      name: xenograftSettingsTab
      label: PDXs and Cell Lines
      group: pixiTabGroup
      active: true
      contents:
        ${pdxPanel}
        ${cellLinePanel}
    hotelSplitterSettingsTab:
      kind: tab
      name: hotelSplitterSettingsTab
      label: Hotel Splitter
      group: pixiTabGroup
      active: true
      contents:
        ${hotelPanel}